/// <reference path="../../typings/tsd.d.ts" />
/// <reference path="../objects/keyboardcontrols.ts" />
/// <reference path="../objects/mousecontrols.ts" />
/// <reference path="../config/screen.ts"/>
/// <reference path="../scenes/scene.ts" />
/// <reference path="../scenes/level1.ts" />
/// <reference path="../scenes/level2.ts" />
/// <reference path="../scenes/level3.ts" />
/// <reference path="../scenes/nextlevel.ts" />
/// <reference path="../scenes/instructions.ts" />
/// <reference path="../scenes/exit.ts" />
/// <reference path="../scenes/over.ts" />
/// <reference path="../scenes/menu.ts" /> 
//# sourceMappingURL=_reference.js.map